### ISSUE TITLE
telegram bot improvement and adding more info

### ISSUE THREAD

**Issue by birizui** [N4rr34n6/TikTok-User-Info-Scraper#2]
I just discovered this tool today, and it's exactly what I’ve been looking for—thank you! I have two suggestions, if they're possible to implement:

Would it be possible to also scrape the links that users include in their profiles, especially the Instagram link when they click the Instagram button?

For the Telegram bot, is there a way to have it run without needing to press "Query TikTok User" every time? Right now, the bot doesn't work unless I manually press that button before sending usernames or IDs.

**Comment by N4rr34n6** [comment]
Hi there! I just implemented both of your suggestions in this commit: 
https://github.com/N4rr34n6/TikTok-User-Info-Scraper/commit/623201db45a9af7bdfcf8969ea4cd8ee1cdda9bc

Changes include:

1. **Profile links extraction**: The bot now extracts all social links from profiles, including:
   - Store/website links from the profile (like Lucasio.store)
   - Instagram and other social media accounts mentioned in bio
   - Email addresses and any other contact information

2. **Simplified workflow**: You no longer need to press "Query TikTok User" before each search. Just send any valid TikTok username directly and the bot will process it automatically.

I've also improved the formatting, added thousand separators for large numbers, and fixed line breaks in bios.

Please give it a try and let me know if this works better for you now or if you have any other suggestions!

**Comment by birizui** [comment]
Thanks for the great upgrades! I tried it out, but it looks like the profile link extraction still isn’t working. It shows the profile URL, but the other social links are still missing.

**Comment by birizui** [comment]
This is the example: 
![Image](https://github.com/user-attachments/assets/e34793b1-dcc5-4cb0-8112-b8ae10a8934a)

**Comment by N4rr34n6** [comment]
I had an error when applying the commit. It is fixed now. Try it now. https://github.com/N4rr34n6/TikTok-User-Info-Scraper/commit/0820f375ce0f0af145bed02a632227a2d1e4a0be

**Comment by birizui** [comment]
It’s partially working now! Turns out it generates the link if it's in the Point 1 format, but it doesn’t extract it when it's in the button form like in Point 2. Is it possible to make it work for the Point 2 buttons as well?

![Image](https://github.com/user-attachments/assets/50ff2aef-a986-41c5-84cf-e689b3885b39)

**Comment by N4rr34n6** [comment]
Send me an example user privately, via TG ([@]n4rr34n6), and I'll study how to do it.

**Comment by kadopol** [comment]
Use your bot with pleasure. Thank you. The country appears as -Region: ES in all queries. Why could this be?

**Comment by N4rr34n6** [comment]
Thank you for your observation and for using my bot. Your feedback is very valuable to help me continue improving.

Indeed, you've spotted a detail that I overlooked during development. The "ES" value that appears in the "Region" section of all queries doesn't actually correspond to TikTok profile data, but rather reflects the location from which my server makes HTTP requests (in this case, Spain).

The issue is that TikTok's API returns this value based on the location of whoever makes the query, not the actual location of the queried user, which makes this information irrelevant for the bot's purpose.

I've fixed this problem by removing this field from the responses, as it doesn't provide useful information about the accounts being queried.

Thank you again for your attention to detail. If you notice anything else that I could improve, please don't hesitate to let me know.

Kind regards.

**Comment by N4rr34n6** [comment]
> Use your bot with pleasure. Thank you. The country appears as -Region: ES in all queries. Why could this be?

Implemented the accurate detection of user regions. The system now correctly identifies and displays the actual region of TikTok users rather than interface configuration values. This improves the overall reliability of geographical data in the OSINT tool.
